/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>


/* Header for class com_tiangou_mp3encoder_Mp3Encoder */

#ifndef _Included_com_tiangou_mp3encoder_Mp3Encoder
#define _Included_com_tiangou_mp3encoder_Mp3Encoder


#ifdef __cplusplus
extern "C" {
#endif

#define LOG_TAG "Mp3Encoder" // 这个是自定义的LOG的标识
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
/*
 * Class:     com_tiangou_mp3encoder_Mp3Encoder
 * Method:    encode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tiangou_mp3encoder_Mp3Encoder_encode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
